name: flutter_realtime_video
description: "A real-time one-on-one video call and screen sharing app using Flutter and WebRTC."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # For WebRTC (video/audio/screen communication)
  flutter_webrtc: ^1.2.0

  # For Signaling (connecting users in real-time)
  cloud_firestore: ^6.0.2
  firebase_core: ^4.1.1

  # For generating random room codes
  random_string: ^2.3.1
  
  # For sharing the room code
  share_plus: ^12.0.0

  # For copying to clipboard
  clipboard: ^2.0.2
  flutter_toastr: ^1.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
