// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM79k55RLBNEylsfZuozBoqSwWHoYVdRA',
    appId: '1:65364816293:web:ce87b3423edead6bd4784c',
    messagingSenderId: '65364816293',
    projectId: 'flutter-realtime-video',
    authDomain: 'flutter-realtime-video.firebaseapp.com',
    databaseURL: 'https://flutter-realtime-video-default-rtdb.firebaseio.com/',
    storageBucket: 'flutter-realtime-video.firebasestorage.app',
    measurementId: 'G-YX634XZX1X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkR1MDNgnoa_hI93D_secrrdSqa4lHcRk',
    appId: '1:65364816293:android:4c90c98d0f522768d4784c',
    messagingSenderId: '65364816293',
    projectId: 'flutter-realtime-video',
    databaseURL: 'https://flutter-realtime-video-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-realtime-video.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeulYMhoXq7xoeeRCSJyZpmyDasdieqUE',
    appId: '1:65364816293:ios:c0d6e719140cb992d4784c',
    messagingSenderId: '65364816293',
    projectId: 'flutter-realtime-video',
    databaseURL: 'https://flutter-realtime-video-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-realtime-video.firebasestorage.app',
    iosBundleId: 'com.example.flutterRealtimeVideo',
  );
}
